#!/bin/bash
### BEGIN INIT INFO
# provides:          mycodo
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:   
# Required-Stop:    
# Short-Description: Start|Stop mycodo.py daemon
# Description:       Start|Stop mycodo.py daemon
### END INIT INFO

case "${1:-''}" in
    'start')
        mkdir -p /var/log/mycodo
        mkdir -p /var/log/mycodo/images
        
        if [ ! -h /var/www/mycodo/images ]; then
            ln -s /var/log/mycodo/images /var/www/mycodo/images
            chown www-data.www-data /var/www/mycodo/images
        fi

        if [ ! -e /var/log/mycodo/sensor-tmp.log ]; then
            touch /var/log/mycodo/sensor-tmp.log
        fi
        if [ ! -e /var/www/mycodo/log/sensor.log ]; then
            touch /var/www/mycodo/log/sensor.log
        fi
        if [ ! -h /var/www/mycodo/log/sensor-tmp.log ]; then
            ln -s /var/log/mycodo/sensor-tmp.log /var/www/mycodo/log/sensor-tmp.log
        fi
        
        if [ ! -e /var/log/mycodo/relay-tmp.log ]; then
            touch /var/log/mycodo/relay-tmp.log
        fi
        if [ ! -e /var/www/mycodo/log/relay.log ]; then
            touch /var/www/mycodo/log/relay.log
        fi
        if [ ! -h /var/www/mycodo/log/relay-tmp.log ]; then
            ln -s /var/log/mycodo/relay-tmp.log /var/www/mycodo/log/relay-tmp.log
        fi
        
        if [ ! -e /var/log/mycodo/daemon-tmp.log ]; then
            touch /var/log/mycodo/daemon-tmp.log
        fi
        if [ ! -e /var/www/mycodo/log/daemon.log ]; then
            touch /var/www/mycodo/log/daemon.log
        fi
        if [ ! -h /var/www/mycodo/log/daemon-tmp.log ]; then
            ln -s /var/log/mycodo/daemon-tmp.log /var/www/mycodo/log/daemon-tmp.log
        fi
        
        chmod -R 770 /var/log/mycodo
        chown -R www-data.www-data /var/log/mycodo
        
        python /var/www/mycodo/cgi-bin/mycodo.py -d s i 2>&1 &
        ;;
    'stop')
        /var/www/mycodo/cgi-bin/mycodo-client.py -t
        
        sleep 10
        
        if ps aux | grep '[m]ycodo.py -d'
        then
            echo "Server is still running"

            PID=`ps aux | grep '[m]ycodo.py -d' | awk '{print $2}'`
            WAIT_SECONDS=10
            count=0

            while kill $PID > /dev/null
            do
                sleep 1
                ((count++))

                # Has the process been killed?
                if ! ps -p $PID > /dev/null ; then
                    break
                fi

                # Have we exceeded $WAIT_SECONDS?
                if [ $count -gt $WAIT_SECONDS ]; then
                    kill -9 $PID
                    break
                fi
            done
            echo "Process with pid $PID has been killed after $count seconds."    
        else
           echo "Server has stopped"
        fi
        ;;
    'restart')
        ;;
    'reload'|'force-reload')
        ;;
    'status')
        ;;
    *)
        echo "Usage: $SELF start|stop"
        exit 1
        ;;
esac
